Jumpscale/core9

- setup.py
-
-
**Version**: 
**Fixes**: #
> Missing 2 last dependencies, developer refactor works

- cmds/js9_getcode_libs_prefab_ays
Fallback to https when cloning repos if cloning via ssh failed
-
-
**Version**: 
**Fixes**: #
> clone with https if failed to clone with git@

- run_tests.sh
- test.sh
-
-
**Version**: 
**Fixes**: #
> dont use container name

- run_tests.sh
-
-
**Version**: 
**Fixes**: #
> start container before running tests

- install/travis_ci/prepare.sh
Allow travis to set GIGBRANCH from the PR branch
-
-
**Version**: 
**Fixes**: #
> stop setting GIGBRANCH env variable

- setup.py
Fix installation error for jumpscale core
-
-
**Version**: 
**Fixes**: #
> update generateplugins function call

- JumpScale9/errorhandling/ErrorHandler.py
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
> Fix path of eco.lua

- cmds/js9_getcode_libs_prefab_ays
- cmds/js9_getcode_portal
-
-
**Version**: 
**Fixes**: #
> Dont fail if GIGBRANCH is not set

- install.sh
- setup.py
-
-
**Version**: 
**Fixes**: #
> Add necessary deps for core9

- JumpScale9/core/InstallTools.py
> fix install tools windows check

- JumpScale9/clients/redis/RedisFactory.py
- JumpScale9/tools/loader/JSLoader.py
- cmds/js9_getcode_libs_prefab_ays
- cmds/js9_getcode_portal
- cmds/js9_init
- setup.py
https://github.com/Jumpscale/developer/issues/56
- backporting fixes from core9 master to 9.0.3 branch
> 903 master backport

- cmds/js9_getcode_portal
Fixes always installing portal from master
-
-
**Version**: 
**Fixes**: #
> fix branch_exists check for portal

- cmds/js9_getcode_libs_prefab_ays
https://github.com/Jumpscale/core9/issues/44
> fix issue with clonging a specific branch

- JumpScale9/core/InstallTools.py
Cleaning up installtools.py 
https://github.com/Jumpscale/core9/issues/3
> init effort to clean install tools

- JumpScale9/errorhandling/ErrorConditionObject.py
- JumpScale9/errorhandling/eco.lua
Get new version of eco.lua
Make sure eco.key is called before serializing
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
> Port eco.lua from jumpscale7

- JumpScale9/fs/SystemFS.py
add onerror handler for shutil rmtree
> fix rmtree on error handler

- JumpScale9/tools/executor/ExecutorBase.py
Fix for setting dirs in executor.
> fix for executor config

- JumpScale9/sal/process/SystemProcess.py
-
-
**Version**: 
**Fixes**: Jumpscale/ays9#255
> Use executable bash in popen 

- JumpScale9/data/key_value_store/redis_store.py
hardening redis models listing
> hardening redis models listing

- JumpScale9/clients/redis/RedisFactory.py
Wait for redis server to start at ays startup.
**Version**: 9.1.2
> wait for redis start

- JumpScale9/data/key_value_store/memory_store.py
> Hardening memory stor. jumpscale/ays9#284

- JumpScale9/core/InstallTools.py
- JumpScale9/tools/executor/ExecutorBase.py
-
-
**Version**: 
**Fixes**: #
> 9.3.0 installation

- JumpScale9/clients/ssh/SSHClientFactory.py
Fixes for ssh client
**Fixes**: https://github.com/Jumpscale/core9/issues/85, https://github.com/Jumpscale/core9/issues/87, https://github.com/Jumpscale/core9/issues/86
> fixes for sshclient

- JumpScale9/data/treemanager/Treemanager.py
- JumpScale9/tools/develop/Nodes.py
- JumpScale9/tools/executor/ExecutorFactory.py
**Fixes**: #https://github.com/Jumpscale/lib9/issues/89
> fix for setting user nodes

- JumpScale9/tools/executor/ExecutorBase.py
fixes installation 
-use j.sal.fs instead of j.do 
**Version**: 
**Fixes**: #
> bug fix in installation

- JumpScale9/fs/SystemFS.py
Simpler and more and more generic path validations
> Cleaned up path validations in SystemFS.py

- install.sh
**Fixes**: https://github.com/Jumpscale/bash/issues/37
> fix install on host

- docs/config/Host_config_and_Dirs_config.md
- docs/config/how_to_add_config.md
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
-
-
**Version**: 
**Fixes**: #
> Adds docs for how to set and get config

- JumpScale9/core/Dirs.py
- JumpScale9/errorhandling/ErrorConditionObject.py
- JumpScale9/fs/SystemFS.py
> fixes for dirs and systemFs

- JumpScale9/clients/git/GitClient.py
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
-
-
**Version**: 
**Fixes**: #
> Adds fix getBranchOrTag

- JumpScale9/core/State.py
- JumpScale9/fs/SystemFS.py
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
-
-
**Version**: 
**Fixes**: #
> Fixes installation on mac

- JumpScale9/__init__.py
**Fixes**: https://github.com/Jumpscale/core9/issues/118
> Fix logging config

- JumpScale9/data/treemanager/Treemanager.py
- JumpScale9/tools/develop/Nodes.py
Make sure hostname is set correctly
raise error on machine names with spaces
> Allow upper case in machine names.

- JumpScale9/data/serializers/SerializerYAML.py
minor bug fix 
-
-
**Version**: 
**Fixes**: #
> minor bug fix

- install/travis_ci/prepare.sh
- run_tests.sh
- test.sh
> add pytest and execute test runner

- JumpScale9/tools/executor/ExecutorBase.py
> Remove cache of executor.exists

- JumpScale9/__init__.py
- JumpScale9/clients/ssh/test_SSHClientFactory.py
- test.sh
Allow importing j namespace to return a mock object when in testing env.
> Mock j namespace in testing mode

- test.sh
> Make sure that we fail the build if test failed

- JumpScale9/sal/process/SystemProcess.py
**Fixes**: https://github.com/Jumpscale/core9/issues/147
> fix process execute

- JumpScale9/tools/configmanager/ConfigManager.py
**Fixes**: https://github.com/Jumpscale/core9/issues/173
> Fix js9_config init

- JumpScale9/tools/bash/BashFactory.py
fix of issue #175 
**Version**: 9.3.0
**Fixes**: #175
> change the manipulation of env vars

- JumpScale9/core/State.py
fix of #159 
**Version**: 9.3.0
**Fixes**: #159
> fix configUpdate behaviour and documentation

- JumpScale9/core/State.py
fix configGetFromDictBool function
**Version**:  9.3.0
**Fixes**: #157
> fix configGetFromDictBool function

- JumpScale9/clients/git/GitClient.py
> Gitclient config methodes

- JumpScale9/tools/configmanager/ConfigManager.py
> fix error in js9_config reset

- JumpScale9/clients/ssh/SSHClient.py
- JumpScale9/clients/ssh/SSHClientFactory.py
- JumpScale9/clients/ssh/SSHClientParamiko.py
- JumpScale9/tools/executor/ExecutorBase.py
- JumpScale9/tools/executor/ExecutorSSH.py
Reintroduces paramiko SSHClient 
**Fixes**:
https://github.com/Jumpscale/lib9/issues/205
> Paramikoclient

- JumpScale9/tools/executor/ExecutorBase.py
- bug fix concerning caching stateonsystem on a global key so cannot have different states for different connections
> executor base and ssh client bug fix

- JumpScale9/clients/redis/RedisFactory.py
- JumpScale9/clients/ssh/SSHClient.py
- JumpScale9/data/tags/Tags.py
- JumpScale9/data/text/Text.py
#243 
-
-
**Version**: 
**Fixes**: #
> Sshclient logger

- README.md
- docs/_sidebar.md
Enable github pages under docs
> Creating _sidebar file
